version: '3.8'
services:
  dev-db:
    image: postgres:alpine
    ports:
      - 5434:5432
    env_file:
      - .env

  test-db:
    image: postgres:alpine
    ports:
      - 5435:5432
    env_file:
      - .env.test.local